language: generic

addons:
    apt:
        packages:
            - g++-6
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
matrix:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          sudo: required
          env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
        - os: osx
          osx_image: xcode7.3
          compiler: clang

before_install:
    - ./.travis/install.sh

branches:
    only:
        - develop
        - test/ci-for-doc

script:
    - cmake projects/cmake && make -j 2 -C projects/cmake
    - .travis/validate.sh
