image:
    - Visual Studio 2015

environment:
    matrix:
        - MSYS_BITS: 64
          ADD_PATH: /mingw64/bin
          platform: x64
        # - HOST_ARCH_ARG: --host=i686-w64-mingw32
        #   MSYS_BITS: 32
        #   ADD_PATH: /mingw64/bin
        #   platform: x32

install:
    - set PATH=
    - C:\msys64\usr\bin\bash -lc "pacman --sync --noconfirm pacman-mirrors"
    - C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
    - C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm" # Hackity hack hacks
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S cmake mingw-w64-{x86_64,i686}-gcc mingw-w64-{x86_64,i686}-libpng mingw-w64-{x86_64,i686}-make"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; git submodule update --init --recursive"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; env"

build_script:
    - set MSYSTEM=MINGW64
    - echo "TESTING Win64"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/projects/cmake; cmake .  -G \"Unix Makefiles\""
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/projects/cmake; make -j 2"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/bin; ./skunit_tests"
    - set MSYSTEM=MINGW32
    - echo "TESTING Win32"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/projects/cmake; rm -rf CMakeFiles Makefile CMakeCache.txt cmake_install.cmake"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/projects/cmake; cmake . -G \"Unix Makefiles\""
    
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/projects/cmake; make -j 2"
    - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/bin; ./skunit_tests"

test: off
